name: Build Flutter APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'  # Adjust if needed

      - name: Install dependencies
        run: flutter pub get
        working-directory: "id id"

      - name: Build APK
        run: flutter build apk --release
        working-directory: "id id"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: "id id/build/app/outputs/flutter-apk/app-release.apk"
